# Generated by Django 4.2 on 2023-08-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0002_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_image',
            field=models.ImageField(default='media\\WIN_20221102_11_55_29_Pro_7tqEr81.jpg', upload_to='media'),
        ),
    ]
