# Generated by Django 4.2 on 2023-08-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0003_books_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_image',
            field=models.ImageField(default='B:\\pyenv\\LibraryProject\\media\\WIN_20221102_11_55_29_Pro.jpg', upload_to='media'),
        ),
    ]
