# Generated by Django 4.2 on 2023-08-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0009_assigned_books_student_cred'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_status',
            field=models.CharField(default='1', max_length=12),
        ),
    ]
