# Generated by Django 4.2 on 2023-08-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0011_alter_books_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_status',
            field=models.CharField(default='available', max_length=12),
        ),
    ]
