# Generated by Django 4.2 on 2023-08-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0012_alter_books_book_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('book_author', models.CharField(max_length=50)),
                ('book_isbn', models.CharField(max_length=20)),
                ('book_total_count', models.IntegerField(max_length=200)),
                ('book_available', models.IntegerField(max_length=200)),
                ('book_lended', models.IntegerField(max_length=200)),
            ],
        ),
    ]
