# Generated by Django 4.2 on 2023-08-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0015_return_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='return_history',
            name='fine_paid',
            field=models.IntegerField(default=0),
        ),
    ]
