# Generated by Django 4.2.4 on 2023-09-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0017_book_pdfs'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_pdfs',
            name='book_image',
            field=models.FileField(default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='book_pdfs',
            name='pdf_file',
            field=models.FileField(default=None, upload_to='pdfs/'),
        ),
    ]
