# Generated by Django 4.2.4 on 2023-09-02 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0018_book_pdfs_book_image_alter_book_pdfs_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='book_image',
        ),
    ]
