# Generated by Django 4.2.1 on 2024-12-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0021_alter_book_pdfs_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_cred',
            name='admin_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='student_cred',
            name='student_id',
            field=models.CharField(default='-', max_length=10, unique=True),
        ),
    ]
